### ISSUE TITLE
New release with PR#10

### ISSUE THREAD

**Issue by markround** [cloudfoundry-community/bind9-boshrelease#11]
Hi, thanks for merging my PR (https://github.com/cloudfoundry-community/bind9-boshrelease/pull/10). Could we please have a new release of this package so we can use it in our manifests without relying on our own dev releases? Many thanks!

**Comment by jhunt** [comment]
Sure!

**Comment by jhunt** [comment]
Try 1.1.1: https://github.com/cloudfoundry-community/bind9-boshrelease/releases/tag/v1.1.1

**Comment by markround** [comment]
Thanks, it works great!
