### ISSUE TITLE
"templates/make_manifest" doesn't exist

### ISSUE THREAD

**Issue by aegershman** [cloudfoundry-community/bind9-boshrelease#16]
In the README, it feels like there's a claim that manifest for bosh-lite or AWS are generated:

```md
For bosh-lite, you can quickly create a deployment manifest & deploy a cluster:

templates/make_manifest warden
bosh -n deploy
For AWS EC2, create a single VM:

templates/make_manifest aws-ec2
bosh -n deploy
```

this folder doesn't exist, and `make_manifest` isn't a file.

Can this be removed from the README? and just have the assumption that the only provided manifest is `manifests/bind9.yml`?

Thanks!

**Comment by jhunt** [comment]
Yeah, I forgot to update the README when I dropped the old ways of make_manifest.  I'll try to get a better README out today or tomorrow.

**Comment by aegershman** [comment]
all good no worries, I've been able to make sense of things using the provided `manifests/bind9.yml` + just reading the `jobs/<job>/spec` files & built opsfiles around that. Thank you for making this available 👍

also out of curiosity, are you aware of any other organization/anyone currently using this?

**Comment by jhunt** [comment]
We use it internally at Stark & Wayne, and several others use it for split-view DNS.
