### ISSUE TITLE
Rolling upgrades and high availability

### ISSUE THREAD

**Issue by aegershman** [cloudfoundry-community/bind9-boshrelease#17]
In order to maintain HA during stemcell repaves, config updates, etc., should the [`max_in_flight` be set to a lower number](https://github.com/cloudfoundry-community/bind9-boshrelease/blob/master/manifests/bind9.yml#L74)? Or is relying on the passed canary & then upgrading every other server at the same time acceptable?

I currently have it configured for `max_in_flight` of 1 because I'm a wuss. But any advice or practical production experience with this deployment is welcome.

## background context

We've been tasked with doing split-horizon DNS to forward certain zones to onprem DNS servers, and public DNS for everything else. Currently, in our BIND9 deployment, we have 1 leader and 3 followers. The BOSH director's cloud config is setup such that every BOSH-managed VM uses the 3 follower VM's IPs for DNS. (It's a backlog item to setup an internal LB which points to these BIND9 VMs, and then configure the cloud-config DNS to use the LB's address)

This works exactly as expected, but the fear is that if the DNS servers are out, _everything_ is out. So I figure it's worth asking if others have had a similar experience / use these BIND servers in a similar fashion, and if they do a less aggressive rolling upgrade on these BIND9 servers.

Thanks a lot 👍

**Comment by jhunt** [comment]
50 is a bit much.  We don't use the sample manifest for anything other than explaining the properties.  It should be safe (nay, advisable!) to drop that to a max_in_flight of 1.

**Comment by aegershman** [comment]
Sick, thanks.

I fully realize yourself / starkandwayne effectively maintains this project, and for all intents and purposes I should be paying for consulting fees, _but I'll try to freeload anyway_:

**Do you have any general advice or "gotchas" to look out for when running this in production?**

If not, that's fine, just figured I'd put the general question out there.

**Comment by jhunt** [comment]
The main thing to keep in mind is that if you are using the AXFR stuff with a master and some replicas, zone changes will normally only affect the master, and the replicas will just transfer down zone changes as they occur, without an interruption of service.

Other than that, don't forget to change your serial numbers when you update the zones, or you'll be quite upset at yourself. 😁

**Comment by aegershman** [comment]
👍gotcha, thank you. _Current_ plan is to have 1 master and 3 replicas, with each replica in separate AZs, and update BOSH cloud-config so every VM has the 3 replicas as their DNS provider... including the BIND9 servers themselves ¯\\_(ツ)_/¯ 

A future enhancement is to have an internal LB with a static IP which points to the deployed BIND9 servers, and configure cloud-config to use that LB's static IP for DNS. That way if/when the IPs of the BIND9 servers changes, we don't have to roll over every single VMs with updated cloud config, we just have to update the LB's targets.

Any thoughts? I promise after this I'll leave you be & close out this issue 😉thanks a lot for your time and advice.

**Comment by jhunt** [comment]
re: 1+3 across AZs sounds perfectly reasonable.

As for load balancing, if you don't have IaaS-provided LBs, you might want to look at keepalived and just have keepalived trade a VIP between the three replicas directly.  We use it primarily with haproxy reverse proxies for HTTP/TCP traffic, in the [load-balancer-boshrelease](https://github.com/genesis-community/load-balancer-boshrelease).  That (haproxy) doesn't support UDP traffic, but keepalived operates at the IP layer so it should be doable.

That would be a fun add-on to this BOSH release, come to think of it. 🤔

Also, you don't have to leave me alone 😁

**Comment by aegershman** [comment]
Nice, will look into the lb boshrelease. I think I'd like that better than IaaS-provided, since it could be standardized & deployed across all our envs (azure, aws, vsphere) with the same topology

How do you feel about this "first mover"/bootstrap situation where you have to setup BOSH, and then use it deploy DNS/LBs/any other infra for the env, and then update all deployments to use the BOSH-deployed infra?

It's not a huge deal since it's really only a problem when getting _started_, but this will be the first time that I have an env which isn't 100% fully declarative... I guess we could use reserved IPs and static IP assignment for the LB in it's manifest, though? That way the entire env is still fully declarative from the get-go... But maybe it's not actually that important to have an env which can be deployed starting from "nothing-to-something" based on git config alone. 

Maybe it's fine to have some values that are dynamic (IPs of LBs, BIND, etc.) & once they're deployed, re-deploy the env with those updated values.

**Comment by aegershman** [comment]
Wait-- if you're using a BOSH-managed LB to load balance DNS, aren't you (sort of) back in the same spot as before, where you have to configure the cloud-config DNS to use the multiple IPs of the LBs? E.g. you'd still have to deploy multiple LBs so you can do rolling upgrades. Right?

I guess the value-add though is that the config options the LB offers, and that you can more-easily scale out DNS servers & just update the LB's routing targets.

EDIT I feel I'm definitely misunderstanding some things. 

> [Keepalived implements the Virtual Routing Resource Protocol (VRRP),
  enabling a single virtual IP (a VIP) to be managed between multiple hosts.
  This in turn allows two or more haproxy servers to present as a single,
  unified endpoint.](https://github.com/genesis-community/load-balancer-boshrelease/blob/master/jobs/keepalived/spec#L2-L7)

[I'll do some reading on `keepalived` 🧐](https://github.com/genesis-community/load-balancer-boshrelease/releases)

Apologies & thanks-- self-hosted LB's & self-hosted DNS is new to me.

**Comment by aegershman** [comment]
Alright, after doing some reading, I realize how this would work. Sorry for the spammy-ness of these comments but I'll post this here for reference in case it helps anyone else.

`keepalived` job co-located on BIND9 servers would be used to share a VIP. When one bind9 goes down & stops heartbeating, a different bind9 instance takes "ownership" of the VIP.

Since `keepalived` is pretty new to me I think **for now**, for simplicity sake, I'll just use the static IPs of the bind9 servers.

With that said in the future maybe I'll experiment with leveraging `keepalived` directly on the bind9 servers OR leveraging `keepalived` on a cluster of nginx UDP LBs (which I also haven't never experimented with, but am under the impression it can do UDP LBing)

I'm not exactly _jazzed_ about self-hosting LBs or split-horizon DNS, but, alas, The Enterprise™ demands it, so it must be done. Who knows though maybe this will work out really well, and if it does, then we'll retrofill all our CF deployments to use this topology just for environmental consistency.

Thanks again 👍
