### ISSUE TITLE
Configurable logging

### ISSUE THREAD

**Issue by aegershman** [cloudfoundry-community/bind9-boshrelease#18]
https://kb.isc.org/docs/aa-01526

Any thoughts on adding a configurable `logging` block so operators can get log lines such as queries made against the server?

Can submit a PR when time permits, figured I'd ask the general question first, though 👍 

feel free to close whenever

**Comment by jhunt** [comment]
Sorry, I missed this issue.  I'm open to whatever, although I personally feel that this BOSH release is sunsetting in favor of more container-y solutions.

**Comment by aegershman** [comment]
Same; I realize it's just not that big of a deal. Thanks though I appreciate it.
